version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - user-service
      - post-service
      - notification-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  user-service:
    build:
      context: ./user-service  # Specify the build context
      dockerfile: Dockerfile   # Optional, specify if you have a custom Dockerfile
    container_name: user-service 
    image: user-service       # Tag the image with a custom name
    ports:
      - "5005:5005"
    depends_on:
      - user-db
    environment:
      - MONGO_URI=mongodb://user-db:27017/user-service-db

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    image: post-service
    ports:
      - "5006:5006"
    depends_on:
      - post-db
      - minio
      - notification-service
      - user-service
    environment:
      - MONGO_URI=mongodb://post-db:27017/post-service-db

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service 
    image: notification-service
    ports:
      - "5007:5007"
    depends_on:
      - notification-db
      - post-db
    environment:
      - MONGO_URI=mongodb://notification-db:27017/notification-service-db

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  user-db:
    image: mongo:4.4
    container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db

  post-db:
    image: mongo:4.4
    container_name: post-db
    ports:
      - "27018:27017"
    volumes:
      - post-data:/data/db

  notification-db:
    image: mongo:4.4
    container_name: notification-db
    ports:
      - "27019:27017"
    volumes:
      - notification-data:/data/db

volumes:
  user-data:
  post-data:
  notification-data:
  minio-data:
